### PR TITLE
Revert "Use upstream gjson"

### PR DESCRIPTION
**Pull request by flavio**
This reverts this merged PR: https://github.com/kubewarden/go-policy-template/pull/22/files

Unfortunately one of the dependencies of gjson is not compatible with TinyGo. Building the template policy leads to the following build time failure:

```console
-: blocking operation in exported function: __guest_call

traceback:
__guest_call
main.validate
fmt.Sprintf
(*fmt.pp).doPrintf
(*fmt.pp).printArg
(*fmt.pp).printValue
internal/fmtsort.Sort
sort.Stable
sort.stable
sort.insertionSort
(sort.Interface).Less
(*github.com/tidwall/pretty.byKeyVal).Less
(*github.com/tidwall/pretty.byKeyVal).isLess
github.com/tidwall/pretty.parsestr
encoding/json.Unmarshal
(*encoding/json.decodeState).unmarshal
(*encoding/json.decodeState).value
(*encoding/json.decodeState).object
encoding/json.cachedTypeFields
(*sync.Map).LoadOrStore
(*sync.Mutex).Lock
make: *** [Makefile:4: policy.wasm] Error 1
```

CC @floriankoch

### CODE REVIEW

**Comment by floriankoch** [comment]
@flavio  hm i tested this with my policy but then i need to take another look on this

**Comment by flavio** [comment]
Wait a second, I think this is working fine with latest release of tinygo (0.23.0). The `Makefile` here is still using `0.18.0`, which explodes with the error from above.

I managed to build it with 0.23.0 and pass the e2e tests.

@floriankoch: can you tell me the version of tinygo you are using?

**Comment by floriankoch** [comment]
@flavio ah - i worked with 0.22

**Comment by flavio** [comment]
You're right. There are however some things that have to be fixed inside of this template repo, I'll fix them with another PR

**Pull request closed without merging**
